version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /tmp/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - franci-app

  app:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=mysql
    networks:
      - franci-app

networks:
  franci-app:
