FROM nginx:1.27.1

# ADD https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-backend-franb0/main/nginx.conf /etc/nginx/nginx.conf
ADD ./nginx.conf /etc/nginx/nginx.conf

ADD https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-frontend-franb0/main/frontend/index.html /usr/share/nginx/html/index.html

ADD https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-frontend-franb0/main/frontend/index.js /usr/share/nginx/html/index.js

ADD https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-frontend-franb0/main/frontend/styles.css /usr/share/nginx/html/styles.css

